// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_play_200_times = "CgkIvbCm2YocEAIQCg"; // <GPGSID>
        public const string achievement_play_100_times = "CgkIvbCm2YocEAIQCQ"; // <GPGSID>
        public const string achievement_play_10_times = "CgkIvbCm2YocEAIQBg"; // <GPGSID>
        public const string leaderboard_high_score__max_combo = "CgkIvbCm2YocEAIQBA"; // <GPGSID>
        public const string leaderboard_high_score__score = "CgkIvbCm2YocEAIQAQ"; // <GPGSID>
        public const string achievement_play_50_times = "CgkIvbCm2YocEAIQCA"; // <GPGSID>
        public const string achievement_play_20_times = "CgkIvbCm2YocEAIQBw"; // <GPGSID>
        public const string leaderboard_total_berries_count = "CgkIvbCm2YocEAIQBQ"; // <GPGSID>
        public const string leaderboard_high_score__count = "CgkIvbCm2YocEAIQAg"; // <GPGSID>
        public const string leaderboard_high_score__kill_all = "CgkIvbCm2YocEAIQAw"; // <GPGSID>

}

